
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index = {
  "default": {
    
    "dropzone-demo": {
      component: React.lazy(() => import("@/registry/convex/examples/dropzone-demo.tsx")),
    }
    ,
    "realtime-cursor-demo": {
      component: React.lazy(() => import("@/registry/convex/examples/realtime-cursor-demo.tsx")),
    }
    ,
    "password-based-auth-demo": {
      component: React.lazy(() => import("@/registry/convex/examples/password-based-auth-demo.tsx")),
    }
    ,
    "current-user-avatar-demo": {
      component: React.lazy(() => import("@/registry/convex/examples/current-user-avatar-demo.tsx")),
    }
    ,
    "realtime-avatar-stack-demo": {
      component: React.lazy(() => import("@/registry/convex/examples/realtime-avatar-stack-demo.tsx")),
    }
    ,
    "realtime-chat-demo": {
      component: React.lazy(() => import("@/registry/convex/examples/realtime-chat-demo.tsx")),
    }
    ,
    "social-auth-demo": {
      component: React.lazy(() => import("@/registry/convex/examples/social-auth-demo.tsx")),
    }
    
  },
} as const
