// typecheck

import { fileURLToPath } from "url";
import fs from "fs";
import path from "path";
import { registry } from "../src/registry/index";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, "..");
const registryPath = path.join(rootDir, "registry.json");
const outputDir = path.join(rootDir, "public", "r");

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const cleanedRegistry = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  ...registry,
  items: registry.items.filter((item) => item.type !== "registry:example"),
};

// Write registry.json at root for shadcn build
fs.writeFileSync(registryPath, JSON.stringify(cleanedRegistry, null, 2));

// Create a registry index file for use by ComponentPreview in the app.
const registryIndex = `
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index = {
  "default": {
    ${registry.items
      .filter((item) => item.type === "registry:example")
      .map((item) => {
        const componentFile = item.files?.find((file) =>
          file.path.endsWith(".tsx"),
        );
        // Strip 'src/' prefix since @/ already maps to ./src/
        const importPath = componentFile?.path.replace(/^src\//, "");

        return `
    "${item.name}": {
      component: ${importPath ? `React.lazy(() => import("@/${importPath}"))` : "null"},
    }
    `;
      })}
  },
} as const
`;
const registryOutputDir = path.join(rootDir, "src", "__registry__");
if (!fs.existsSync(registryOutputDir)) {
  fs.mkdirSync(registryOutputDir, { recursive: true });
}
fs.writeFileSync(path.join(registryOutputDir, "index.tsx"), registryIndex);
